import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Set page title and layout
st.set_page_config(page_title='FDApp', layout='wide')

# Add a title and a subheader
st.title('Transaction Fraud Detection Application')
st.subheader('Please select the model and input the features to predict the output.')

customer_job = {'software': 1, 'mathematician': 2, 'scientist': 3, 'teaching': 4, 'airline': 5, 'medicine': 6, 'marketing': 7, 'nature': 8, 'trader': 9, 'lawyer': 10, 'journalism': 11, 'finance': 12, 'civil': 13, 'executive': 14, 'media': 15, 'sports': 16, 'designer': 17, 'politician': 18, 'food': 19, 'other_engineering': 20, 'travel': 21, 'manager': 22, 'real_estate': 23, 'entertainment': 24}
product_category = {'grocery_net': 1, 'kids_pets': 2, 'shopping_pos': 3, 'home': 4, 'gas_transport': 5, 'food_dining': 6, 'entertainment': 7, 'health_fitness': 8, 'shopping_net': 9, 'travel': 10, 'misc_pos': 11, 'misc_net': 12, 'grocery_pos': 13, 'personal_care': 14}
merhcant = {'fraud_Runolfsson and Sons': 1, 'fraud_Larkin Ltd': 2, 'fraud_Metz-Boehm': 3, 'fraud_Quitzon-Goyette': 4, 'fraud_Turner and Sons': 5, 'fraud_Jacobi and Sons': 6, 'fraud_Raynor, Reinger and Hagenes': 7, 'fraud_Bechtelar-Rippin': 8, 'fraud_Brekke and Sons': 9, 'fraud_Pouros, Walker and Spencer': 10, 'fraud_Grimes LLC': 11, 'fraud_Erdman-Durgan': 12, 'fraud_Towne, Greenholt and Koepp': 13, 'fraud_Christiansen, Goyette and Schamberger': 14, 'fraud_Rodriguez Group': 15, 'fraud_Corwin-Romaguera': 16, 'fraud_Conroy Ltd': 17, 'fraud_Herzog Ltd': 18, 'fraud_Graham, Hegmann and Hammes': 19, 'fraud_Schumm PLC': 20, 'fraud_Roob-Okuneva': 21, 'fraud_Robel, Cummerata and Prosacco': 22, 'fraud_Nolan-Williamson': 23, 'fraud_Berge-Hills': 24, "fraud_O'Reilly, Mohr and Purdy": 25, 'fraud_Schaefer, Maggio and Daugherty': 26, 'fraud_Kuphal-Bartoletti': 27, 'fraud_Bernier, Streich and Jewess': 28, 'fraud_Bradtke PLC': 29, 'fraud_Stoltenberg-Beatty': 30, 'fraud_Weimann, Kuhic and Beahan': 31, 'fraud_Frami Group': 32, 'fraud_Schaefer, McGlynn and Bosco': 33, 'fraud_Bode-Schuster': 34, 'fraud_Hills-Witting': 35, 'fraud_Reichert, Shanahan and Hayes': 36, 'fraud_Reilly LLC': 37, 'fraud_Greenfelder, Bartoletti and Davis': 38, 'fraud_Huel-Langworth': 39, 'fraud_Yost, Schamberger and Windler': 40, 'fraud_Erdman-Kertzmann': 41, 'fraud_Kris-Weimann': 42, 'fraud_Price Inc': 43, 'fraud_Moore, Williamson and Emmerich': 44, 'fraud_Fadel, Mertz and Rippin': 45, 'fraud_Schuppe, Nolan and Hoeger': 46, 'fraud_Hudson-Ratke': 47, 'fraud_Kutch, Hermiston and Farrell': 48, 'fraud_White and Sons': 49, "fraud_Greenholt, O'Hara and Balistreri": 50, 'fraud_Predovic Inc': 51, 'fraud_Weimann-Lockman': 52, 'fraud_Barton LLC': 53, 'fraud_Schoen, Kuphal and Nitzsche': 54, 'fraud_Lowe, Dietrich and Erdman': 55, 'fraud_Zemlak, Tillman and Cremin': 56, 'fraud_Homenick LLC': 57, 'fraud_Kilback LLC': 58, 'fraud_Jakubowski Group': 59, 'fraud_Terry, Johns and Bins': 60, 'fraud_Powlowski-Weimann': 61, 'fraud_Okuneva, Schneider and Rau': 62, 'fraud_Streich Ltd': 63, 'fraud_Brown PLC': 64, 'fraud_Bins-Howell': 65, 'fraud_Breitenberg-Hermiston': 66, 'fraud_Daugherty LLC': 67, 'fraud_Schroeder, Hauck and Treutel': 68, 'fraud_Hudson-Grady': 69, 'fraud_Howe Ltd': 70, 'fraud_Koss and Sons': 71, 'fraud_Yost-Rogahn': 72, 'fraud_Corwin-Gorczany': 73, 'fraud_Reichert-Weissnat': 74, 'fraud_Kerluke-Abshire': 75, 'fraud_Hermann-Gaylord': 76, "fraud_Lesch, D'Amore and Brown": 77, 'fraud_Block-Parisian': 78, 'fraud_Rolfson-Kunde': 79, 'fraud_Bahringer, Bergnaum and Quitzon': 80, 'fraud_Goodwin-Nitzsche': 81, 'fraud_Haag-Blanda': 82, 'fraud_Keeling-Crist': 83, 'fraud_Koss, Hansen and Lueilwitz': 84, 'fraud_Jast-McDermott': 85, 'fraud_Berge LLC': 86, 'fraud_Jewess LLC': 87, 'fraud_Dickinson-Rempel': 88, 'fraud_Stamm-Witting': 89, 'fraud_Hackett-Lueilwitz': 90, "fraud_Schamberger-O'Keefe": 91, 'fraud_Mohr Inc': 92, 'fraud_Kihn, Brakus and Goyette': 93, 'fraud_Erdman-Schaden': 94, 'fraud_Rutherford-Mertz': 95, 'fraud_Stamm-Rodriguez': 96, 'fraud_Stanton, Jakubowski and Baumbach': 97, 'fraud_Kiehn Inc': 98, 'fraud_Gerlach Inc': 99, 'fraud_Fahey Inc': 100, 'fraud_Reilly, Heaney and Cole': 101, 'fraud_Hoppe, Harris and Bednar': 102, 'fraud_Cassin-Harvey': 103, 'fraud_Ernser-Feest': 104, 'fraud_Heller, Gutmann and Zieme': 105, 'fraud_Fritsch and Sons': 106, 'fraud_Bins-Tillman': 107, 'fraud_Kozey-Kuhlman': 108, "fraud_O'Hara-Wilderman": 109, 'fraud_Goldner, Kovacek and Abbott': 110, 'fraud_Botsford PLC': 111, 'fraud_Halvorson Group': 112, 'fraud_Heller-Langosh': 113, 'fraud_Schuppe-Schuppe': 114, 'fraud_Veum-Koelpin': 115, 'fraud_Schimmel-Olson': 116, 'fraud_Auer-Mosciski': 117, 'fraud_Kub-Heaney': 118, 'fraud_Quitzon, Green and Bashirian': 119, 'fraud_Cummings LLC': 120, 'fraud_Pfeffer and Sons': 121, 'fraud_Wuckert-Walter': 122, 'fraud_Schmeler Inc': 123, 'fraud_McDermott-Weimann': 124, 'fraud_Harris Inc': 125, 'fraud_Pacocha-Bauch': 126, 'fraud_Schroeder Group': 127, 'fraud_Roberts, Daniel and Macejkovic': 128, 'fraud_Welch, Rath and Koepp': 129, 'fraud_Nitzsche, Kessler and Wolff': 130, 'fraud_Boyer-Reichert': 131, 'fraud_Sporer Inc': 132, 'fraud_Volkman-Predovic': 133, 'fraud_Beier and Sons': 134, 'fraud_Emmerich-Luettgen': 135, 'fraud_Lesch Ltd': 136, 'fraud_Miller-Harris': 137, 'fraud_Pagac LLC': 138, 'fraud_Schoen Ltd': 139, 'fraud_Vandervort-Funk': 140, 'fraud_Bailey-Morar': 141, 'fraud_Medhurst, Cartwright and Ebert': 142, "fraud_O'Connell-Ullrich": 143, 'fraud_Altenwerth-Kilback': 144, 'fraud_Dicki Ltd': 145, 'fraud_Eichmann, Bogan and Rodriguez': 146, 'fraud_Bogisich Inc': 147, 'fraud_Smitham-Schiller': 148, 'fraud_Zulauf LLC': 149, 'fraud_Shanahan-Lehner': 150, 'fraud_Gulgowski LLC': 151, 'fraud_Kuhic Inc': 152, 'fraud_Berge, Kautzer and Harris': 153, 'fraud_Waters-Cruickshank': 154, 'fraud_Hahn, Bahringer and McLaughlin': 155, 'fraud_Reinger, Weissnat and Strosin': 156, 'fraud_Bernhard Inc': 157, 'fraud_Kutch-Wilderman': 158, 'fraud_Morissette LLC': 159, 'fraud_Huel, Hammes and Witting': 160, 'fraud_Bashirian Group': 161, 'fraud_Padberg-Welch': 162, 'fraud_Kiehn-Emmerich': 163, 'fraud_Runte, Green and Emard': 164, 'fraud_Morissette PLC': 165, 'fraud_Zboncak Ltd': 166, 'fraud_Hintz, Bauch and Smith': 167, 'fraud_Harris Group': 168, 'fraud_Thiel PLC': 169, 'fraud_Macejkovic-Lesch': 170, 'fraud_Nienow PLC': 171, 'fraud_Ullrich Ltd': 172, 'fraud_Bernier, Volkman and Hoeger': 173, 'fraud_Bins, Balistreri and Beatty': 174, 'fraud_Harber Inc': 175, 'fraud_Goyette-Gerhold': 176, 'fraud_Parisian, Schiller and Altenwerth': 177, 'fraud_Herman Inc': 178, 'fraud_Kilback Group': 179, 'fraud_Johnson, Runolfsdottir and Mayer': 180, 'fraud_Swift PLC': 181, 'fraud_Cormier LLC': 182, 'fraud_Auer-West': 183, 'fraud_Hettinger, McCullough and Fay': 184, 'fraud_Heathcote, Yost and Kertzmann': 185, 'fraud_Miller-Hauck': 186, 'fraud_Schmitt Inc': 187, 'fraud_Kuhn LLC': 188, 'fraud_Torphy-Goyette': 189, 'fraud_Nader-Heller': 190, 'fraud_Jerde-Hermann': 191, 'fraud_Streich, Dietrich and Barton': 192, 'fraud_Treutel-King': 193, 'fraud_Stokes, Christiansen and Sipes': 194, 'fraud_Windler, Goodwin and Kovacek': 195, 'fraud_Will Ltd': 196, 'fraud_Bahringer, Schoen and Corkery': 197, 'fraud_Hills-Boyer': 198, 'fraud_Graham and Sons': 199, 'fraud_Streich, Rolfson and Wilderman': 200, 'fraud_DuBuque LLC': 201, 'fraud_Rippin-VonRueden': 202, 'fraud_Stiedemann Ltd': 203, 'fraud_McCullough Group': 204, 'fraud_Ratke and Sons': 205, 'fraud_Lind-Buckridge': 206, 'fraud_Conroy-Emard': 207, 'fraud_McKenzie-Huels': 208, 'fraud_Bednar Group': 209, 'fraud_Konopelski, Schneider and Hartmann': 210, "fraud_O'Keefe-Wisoky": 211, 'fraud_Conroy-Cruickshank': 212, 'fraud_Weber and Sons': 213, 'fraud_Lang, Towne and Schuppe': 214, "fraud_Hamill-D'Amore": 215, 'fraud_Bernier and Sons': 216, 'fraud_Moore, Dibbert and Koepp': 217, 'fraud_Leannon-Nikolaus': 218, 'fraud_Jakubowski Inc': 219, 'fraud_Brown Inc': 220, 'fraud_Stroman, Hudson and Erdman': 221, 'fraud_Romaguera, Cruickshank and Greenholt': 222, 'fraud_Hamill-Daugherty': 223, 'fraud_Jaskolski-Vandervort': 224, 'fraud_Gottlieb, Considine and Schultz': 225, 'fraud_Wilkinson PLC': 226, 'fraud_Heller PLC': 227, 'fraud_Fadel-Hilpert': 228, 'fraud_Swaniawski, Lowe and Robel': 229, 'fraud_Gottlieb Group': 230, 'fraud_Leffler-Goldner': 231, 'fraud_Kuphal-Predovic': 232, 'fraud_Kutch, Steuber and Gerhold': 233, 'fraud_Reichert, Rowe and Mraz': 234, "fraud_O'Connell, Botsford and Hand": 235, 'fraud_Friesen-Ortiz': 236, 'fraud_Mante, Luettgen and Hackett': 237, 'fraud_Rau and Sons': 238, 'fraud_Kihn, Abernathy and Douglas': 239, 'fraud_Turcotte, Batz and Buckridge': 240, 'fraud_Zboncak, Rowe and Murazik': 241, 'fraud_Eichmann-Kilback': 242, 'fraud_Prohaska-Murray': 243, 'fraud_Schaefer, Fay and Hilll': 244, 'fraud_Swaniawski, Nitzsche and Welch': 245, 'fraud_Donnelly PLC': 246, 'fraud_Medhurst PLC': 247, 'fraud_Rohan, White and Aufderhar': 248, 'fraud_Maggio-Fahey': 249, 'fraud_Reichel LLC': 250, 'fraud_Stracke-Lemke': 251, 'fraud_Monahan-Morar': 252, 'fraud_Connelly-Carter': 253, 'fraud_Gibson-Deckow': 254, 'fraud_Waelchi Inc': 255, 'fraud_Bernhard-Lesch': 256, 'fraud_Wuckert-Goldner': 257, 'fraud_Christiansen-Gusikowski': 258, 'fraud_Hagenes, Kohler and Hoppe': 259, 'fraud_Friesen-Stamm': 260, 'fraud_Nienow, Barrows and Romaguera': 261, 'fraud_Raynor, Feest and Miller': 262, 'fraud_Haley, Jewess and Bechtelar': 263, 'fraud_Huels-Hahn': 264, 'fraud_Dare, Fritsch and Zboncak': 265, 'fraud_Bartoletti-Wunsch': 266, 'fraud_Hickle Group': 267, 'fraud_Kautzer and Sons': 268, 'fraud_Fisher Inc': 269, 'fraud_Denesik, Powlowski and Pouros': 270, 'fraud_Stark-Batz': 271, 'fraud_Goyette Inc': 272, 'fraud_Schumm, Bauch and Ondricka': 273, 'fraud_Jacobi Inc': 274, 'fraud_Klocko, Runolfsdottir and Breitenberg': 275, 'fraud_Connelly, Reichert and Fritsch': 276, 'fraud_Wuckert, Wintheiser and Friesen': 277, 'fraud_Eichmann, Hayes and Treutel': 278, 'fraud_Towne LLC': 279, 'fraud_Brown-Greenholt': 280, 'fraud_Schmidt-Larkin': 281, 'fraud_Emmerich-Rau': 282, 'fraud_Daugherty, Pouros and Beahan': 283, 'fraud_Hermann and Sons': 284, 'fraud_Rowe, Batz and Goodwin': 285, 'fraud_Morissette-Schaefer': 286, 'fraud_Larson-Moen': 287, 'fraud_Ebert-Daugherty': 288, 'fraud_Terry Ltd': 289, 'fraud_Dickinson Ltd': 290, 'fraud_Cronin, Kshlerin and Weber': 291, 'fraud_Wilkinson Ltd': 292, 'fraud_Hammes-Beatty': 293, 'fraud_Schiller, Blanda and Johnson': 294, 'fraud_Cartwright PLC': 295, 'fraud_Padberg-Sauer': 296, 'fraud_Gerhold LLC': 297, 'fraud_Hartmann, Rowe and Hermann': 298, 'fraud_Mohr-Bayer': 299, 'fraud_Gislason Group': 300, 'fraud_Beer-Jast': 301, 'fraud_Dare, Casper and Bartoletti': 302, 'fraud_Mayert Group': 303, 'fraud_Kassulke PLC': 304, 'fraud_Crist, Jakubowski and Littel': 305, 'fraud_Beier LLC': 306, 'fraud_Rempel Inc': 307, 'fraud_Collier Inc': 308, 'fraud_Jenkins, Hauck and Friesen': 309, 'fraud_McGlynn-Jaskolski': 310, 'fraud_Goyette-Herzog': 311, 'fraud_Jaskolski-Dibbert': 312, 'fraud_Ruecker-Mayert': 313, 'fraud_Kris-Padberg': 314, 'fraud_Klein Group': 315, 'fraud_Cruickshank-Mills': 316, 'fraud_Hahn, Douglas and Schowalter': 317, 'fraud_Baumbach, Hodkiewicz and Walsh': 318, 'fraud_Reichert, Huels and Hoppe': 319, 'fraud_Casper, Hand and Zulauf': 320, 'fraud_Turcotte, McKenzie and Koss': 321, 'fraud_Nienow, Ankunding and Collier': 322, 'fraud_Larkin, Stracke and Greenfelder': 323, 'fraud_Ernser-Lynch': 324, 'fraud_Lubowitz-Walter': 325, 'fraud_Friesen Inc': 326, 'fraud_Cummerata-Jones': 327, 'fraud_Jast and Sons': 328, 'fraud_Dooley Inc': 329, 'fraud_Altenwerth, Cartwright and Koss': 330, 'fraud_Cummerata-Hilpert': 331, 'fraud_Kuphal-Toy': 332, 'fraud_Kilback and Sons': 333, 'fraud_Effertz LLC': 334, 'fraud_Roob, Conn and Tremblay': 335, 'fraud_Heathcote LLC': 336, 'fraud_Rau-Grant': 337, 'fraud_Greenholt Ltd': 338, 'fraud_Lockman Ltd': 339, 'fraud_Sporer-Keebler': 340, 'fraud_Beier-Hyatt': 341, 'fraud_Wolf Inc': 342, 'fraud_Cormier, Stracke and Thiel': 343, 'fraud_Ritchie, Bradtke and Stiedemann': 344, 'fraud_Lind, Huel and McClure': 345, 'fraud_Collier LLC': 346, 'fraud_Bruen-Yost': 347, 'fraud_Adams-Barrows': 348, 'fraud_Carroll PLC': 349, 'fraud_Koepp-Witting': 350, 'fraud_Fritsch LLC': 351, 'fraud_Reilly and Sons': 352, 'fraud_Champlin and Sons': 353, 'fraud_Willms, Kris and Bergnaum': 354, 'fraud_Lynch-Mohr': 355, 'fraud_Kihn Inc': 356, 'fraud_McDermott-Rice': 357, 'fraud_Kling-Ernser': 358, 'fraud_Turcotte-Halvorson': 359, 'fraud_Renner Ltd': 360, 'fraud_Howe PLC': 361, 'fraud_Romaguera, Wehner and Tromp': 362, 'fraud_Kuhic, Bins and Pfeffer': 363, 'fraud_Stark-Koss': 364, 'fraud_Bartoletti and Sons': 365, 'fraud_Dach-Borer': 366, 'fraud_Parker, Nolan and Trantow': 367, 'fraud_Volkman Ltd': 368, 'fraud_Murray-Smitham': 369, 'fraud_Hermiston, Pacocha and Smith': 370, 'fraud_Gottlieb-Hansen': 371, 'fraud_Haley, Batz and Auer': 372, 'fraud_Labadie, Treutel and Bode': 373, 'fraud_Huels-Nolan': 374, 'fraud_Thiel-Thiel': 375, 'fraud_Swaniawski, Bahringer and Ledner': 376, 'fraud_Cartwright-Harris': 377, 'fraud_Feil-Morar': 378, 'fraud_Lockman, West and Runte': 379, 'fraud_Kemmer-Buckridge': 380, 'fraud_Schuppe LLC': 381, 'fraud_Koelpin and Sons': 382, 'fraud_Brown, Homenick and Lesch': 383, 'fraud_Ledner-Pfannerstill': 384, 'fraud_Little Ltd': 385, 'fraud_Ruecker Group': 386, 'fraud_Skiles-Ankunding': 387, 'fraud_McDermott, Osinski and Morar': 388, 'fraud_Metz, Russel and Metz': 389, 'fraud_Schroeder, Wolff and Hermiston': 390, 'fraud_Hackett Group': 391, 'fraud_Stehr, Jewess and Schimmel': 392, 'fraud_Bahringer, Osinski and Block': 393, 'fraud_Hoppe-Parisian': 394, 'fraud_Corwin-Collins': 395, 'fraud_Kling-Grant': 396, 'fraud_Stiedemann Inc': 397, 'fraud_Witting, Beer and Ernser': 398, 'fraud_Friesen Ltd': 399, 'fraud_Pouros-Conroy': 400, 'fraud_Hintz-Bruen': 401, 'fraud_Kirlin and Sons': 402, 'fraud_Mraz-Herzog': 403, 'fraud_Bins-Rice': 404, 'fraud_Medhurst, Labadie and Gottlieb': 405, 'fraud_Bernhard, Grant and Langworth': 406, 'fraud_Monahan, Hermann and Johns': 407, 'fraud_Emard Inc': 408, 'fraud_Greenholt, Jacobi and Gleason': 409, 'fraud_Schaefer Ltd': 410, 'fraud_Hirthe-Beier': 411, 'fraud_Funk Group': 412, 'fraud_Schultz, Simonis and Little': 413, 'fraud_Kovacek, Dibbert and Ondricka': 414, 'fraud_Fisher-Schowalter': 415, 'fraud_Kuvalis Ltd': 416, 'fraud_Denesik and Sons': 417, 'fraud_Skiles LLC': 418, 'fraud_Kutch LLC': 419, 'fraud_Tillman, Dickinson and Labadie': 420, 'fraud_Adams, Kovacek and Kuhlman': 421, 'fraud_Herman, Treutel and Dickens': 422, 'fraud_Torp-Labadie': 423, 'fraud_Padberg-Rogahn': 424, 'fraud_Baumbach, Feeney and Morar': 425, 'fraud_Schumm, McLaughlin and Carter': 426, 'fraud_Medhurst Inc': 427, 'fraud_Labadie LLC': 428, 'fraud_Hauck, Dietrich and Funk': 429, 'fraud_Heidenreich PLC': 430, 'fraud_Lebsack and Sons': 431, 'fraud_Conroy, Balistreri and Gorczany': 432, "fraud_Pacocha-O'Reilly": 433, 'fraud_Gaylord-Powlowski': 434, 'fraud_Ankunding-Carroll': 435, 'fraud_Kunde-Sanford': 436, 'fraud_Koepp-Parker': 437, 'fraud_Kutch-Ferry': 438, 'fraud_Morar Inc': 439, 'fraud_Schoen-Quigley': 440, 'fraud_Huel Ltd': 441, 'fraud_Marvin-Lind': 442, 'fraud_Gutmann, McLaughlin and Wiza': 443, 'fraud_Romaguera Ltd': 444, 'fraud_Heaney-Marquardt': 445, 'fraud_Roob LLC': 446, 'fraud_Torp-Lemke': 447, 'fraud_Dibbert and Sons': 448, 'fraud_Buckridge PLC': 449, 'fraud_Watsica LLC': 450, 'fraud_Zemlak Group': 451, 'fraud_Hilpert-Conroy': 452, 'fraud_Schulist Ltd': 453, 'fraud_Mosciski, Gislason and Mertz': 454, 'fraud_Baumbach, Strosin and Nicolas': 455, 'fraud_Kunze, Larkin and Mayert': 456, 'fraud_Doyle Ltd': 457, 'fraud_Spinka Inc': 458, 'fraud_Bogisich-Homenick': 459, 'fraud_Boyer PLC': 460, 'fraud_Hills-Olson': 461, 'fraud_Rutherford, Homenick and Bergstrom': 462, 'fraud_Lemke-Gutmann': 463, 'fraud_Langosh, Wintheiser and Hyatt': 464, 'fraud_Dach-Nader': 465, 'fraud_Olson, Becker and Koch': 466, 'fraud_Pollich LLC': 467, 'fraud_Satterfield-Lowe': 468, 'fraud_Dare-Marvin': 469, 'fraud_Bode-Rempel': 470, 'fraud_Windler LLC': 471, 'fraud_Dooley-Thompson': 472, 'fraud_Pfeffer LLC': 473, 'fraud_Botsford Ltd': 474, 'fraud_Spinka-Welch': 475, 'fraud_Kling Inc': 476, 'fraud_Kuhic LLC': 477, 'fraud_Gleason and Sons': 478, 'fraud_Ledner, Hartmann and Feest': 479, 'fraud_Spencer-Runolfsson': 480, 'fraud_Rau-Robel': 481, 'fraud_Kunze Inc': 482, 'fraud_Crona and Sons': 483, 'fraud_Block-Hauck': 484, 'fraud_Berge-Ullrich': 485, 'fraud_Kutch and Sons': 486, 'fraud_Marks Inc': 487, 'fraud_Deckow-Dare': 488, 'fraud_Waelchi-Wolf': 489, 'fraud_Hayes, Marquardt and Dibbert': 490, 'fraud_Fadel Inc': 491, 'fraud_Auer LLC': 492, 'fraud_Dietrich-Fadel': 493, 'fraud_Durgan, Gislason and Spencer': 494, 'fraud_Hodkiewicz, Prohaska and Paucek': 495, 'fraud_Mosciski, Ziemann and Farrell': 496, 'fraud_Reichel, Bradtke and Blanda': 497, 'fraud_Bauch-Blanda': 498, 'fraud_Turner, Ruecker and Parisian': 499, 'fraud_Bradtke, Torp and Bahringer': 500, 'fraud_Schiller Ltd': 501, 'fraud_Gleason-Macejkovic': 502, 'fraud_Schmeler, Bashirian and Price': 503, 'fraud_Dare-Gibson': 504, 'fraud_Gutmann-Upton': 505, 'fraud_Rodriguez, Yost and Jenkins': 506, 'fraud_Feil, Hilpert and Koss': 507, 'fraud_Kerluke Inc': 508, 'fraud_Lynch-Wisozk': 509, 'fraud_Cole PLC': 510, 'fraud_Romaguera and Sons': 511, 'fraud_Yost, Block and Koepp': 512, 'fraud_Pacocha-Weissnat': 513, 'fraud_Balistreri-Nader': 514, 'fraud_Paucek-Wiza': 515, 'fraud_Little, Gutmann and Lynch': 516, 'fraud_Schmidt and Sons': 517, 'fraud_Kihn-Fritsch': 518, 'fraud_Thiel Ltd': 519, 'fraud_Kilback, Nitzsche and Leffler': 520, 'fraud_Schneider, Hayes and Nikolaus': 521, 'fraud_Kessler Inc': 522, 'fraud_Shields-Wunsch': 523, 'fraud_VonRueden Group': 524, 'fraud_Connelly PLC': 525, 'fraud_Ziemann-Waters': 526, 'fraud_Sawayn PLC': 527, 'fraud_Wisozk and Sons': 528, 'fraud_Rippin, Kub and Mann': 529, 'fraud_Kub PLC': 530, 'fraud_Osinski Inc': 531, 'fraud_Tillman, Fritsch and Schmitt': 532, 'fraud_Bogisich-Weimann': 533, 'fraud_Prosacco, Kreiger and Kovacek': 534, 'fraud_Durgan-Auer': 535, 'fraud_Gutmann Ltd': 536, "fraud_O'Keefe-Hudson": 537, 'fraud_Upton PLC': 538, 'fraud_Welch Inc': 539, 'fraud_Johns-Hoeger': 540, 'fraud_Botsford and Sons': 541, 'fraud_Luettgen PLC': 542, 'fraud_Smith-Stokes': 543, 'fraud_Schoen, Nienow and Bauch': 544, 'fraud_Erdman-Ebert': 545, 'fraud_Nader-Maggio': 546, 'fraud_Smitham-Boehm': 547, 'fraud_Kohler, Lindgren and Koelpin': 548, 'fraud_Parker-Kunde': 549, 'fraud_Wiza, Schaden and Stark': 550, 'fraud_Lynch Ltd': 551, 'fraud_Armstrong, Walter and Gottlieb': 552, 'fraud_Bauch-Raynor': 553, 'fraud_Wilkinson LLC': 554, 'fraud_Ruecker, Beer and Collier': 555, 'fraud_McCullough LLC': 556, 'fraud_McLaughlin, Armstrong and Koepp': 557, 'fraud_Wiza LLC': 558, 'fraud_Streich, Hansen and Veum': 559, 'fraud_Turner, Ziemann and Lehner': 560, 'fraud_Hyatt, Russel and Gleichner': 561, 'fraud_Daugherty-Thompson': 562, 'fraud_Ferry, Lynch and Kautzer': 563, 'fraud_Bahringer Group': 564, 'fraud_Block Group': 565, 'fraud_Osinski, Ledner and Leuschke': 566, 'fraud_Ankunding LLC': 567, 'fraud_Langworth, Boehm and Gulgowski': 568, 'fraud_Schmitt Ltd': 569, 'fraud_Runte-Mohr': 570, 'fraud_Johnston, Nikolaus and Maggio': 571, 'fraud_Pouros-Haag': 572, 'fraud_Simonis-Prohaska': 573, 'fraud_McGlynn-Heathcote': 574, 'fraud_Barton Inc': 575, 'fraud_Swift, Bradtke and Marquardt': 576, 'fraud_Becker, Harris and Harvey': 577, 'fraud_Hills, Hegmann and Schaefer': 578, 'fraud_Leannon-Ward': 579, 'fraud_Parisian and Sons': 580, 'fraud_Lehner, Mosciski and King': 581, 'fraud_Goyette, Howell and Collier': 582, 'fraud_Cremin, Hamill and Reichel': 583, 'fraud_Ferry, Reichel and DuBuque': 584, 'fraud_Champlin-Casper': 585, 'fraud_Lubowitz, Terry and Stracke': 586, 'fraud_Walter, Hettinger and Kessler': 587, 'fraud_Trantow PLC': 588, 'fraud_Eichmann-Russel': 589, 'fraud_Lehner, Reichert and Mills': 590, 'fraud_Douglas, Schneider and Turner': 591, 'fraud_Baumbach Ltd': 592, 'fraud_Watsica, Haag and Considine': 593, 'fraud_Koss, McLaughlin and Mayer': 594, 'fraud_Barrows PLC': 595, 'fraud_Heller-Abshire': 596, 'fraud_Boehm, Block and Jakubowski': 597, 'fraud_Abshire PLC': 598, 'fraud_Kihn-Schuster': 599, 'fraud_Cole, Hills and Jewess': 600, 'fraud_Volkman PLC': 601, 'fraud_Kertzmann LLC': 602, 'fraud_Ritchie, Oberbrunner and Cremin': 603, 'fraud_Spencer PLC': 604, 'fraud_Abernathy and Sons': 605, 'fraud_Donnelly LLC': 606, 'fraud_Flatley-Durgan': 607, 'fraud_Torphy-Kertzmann': 608, 'fraud_Harris, Gusikowski and Heaney': 609, 'fraud_Johns Inc': 610, 'fraud_Kuhn Group': 611, 'fraud_Tromp, Kerluke and Glover': 612, 'fraud_Williamson LLC': 613, "fraud_Friesen-D'Amore": 614, 'fraud_Kassulke Inc': 615, 'fraud_Jones, Sawayn and Romaguera': 616, 'fraud_Kerluke, Considine and Macejkovic': 617, 'fraud_Kutch-Hegmann': 618, 'fraud_Boehm, Predovic and Reinger': 619, 'fraud_Bahringer-Streich': 620, 'fraud_Lemke and Sons': 621, 'fraud_Moen, Reinger and Murphy': 622, 'fraud_Rowe-Vandervort': 623, 'fraud_Zieme, Bode and Dooley': 624, 'fraud_Flatley Group': 625, 'fraud_Larson, Quitzon and Spencer': 626, 'fraud_Morissette, Weber and Wiegand': 627, "fraud_Deckow-O'Conner": 628, 'fraud_Jast Ltd': 629, 'fraud_Prosacco LLC': 630, 'fraud_Nicolas, Hills and McGlynn': 631, 'fraud_Towne, Walker and Borer': 632, 'fraud_Kris-Kertzmann': 633, 'fraud_Little-Gleichner': 634, 'fraud_Klocko LLC': 635, 'fraud_Douglas, DuBuque and McKenzie': 636, 'fraud_Langworth LLC': 637, 'fraud_Reichel Inc': 638, 'fraud_Tillman LLC': 639, 'fraud_Kling, Howe and Schneider': 640, 'fraud_Bednar PLC': 641, 'fraud_Roberts, Ryan and Smith': 642, 'fraud_Crooks and Sons': 643, 'fraud_Goldner-Lemke': 644, 'fraud_Douglas-White': 645, 'fraud_Hyatt-Blick': 646, 'fraud_Reynolds-Schinner': 647, 'fraud_Kerluke, Kertzmann and Wiza': 648, 'fraud_Shields Inc': 649, 'fraud_Kulas Group': 650, 'fraud_Bahringer-Larson': 651, 'fraud_Dibbert-Green': 652, 'fraud_Wintheiser, Dietrich and Schimmel': 653, 'fraud_Torp, Muller and Borer': 654, 'fraud_Monahan, Bogisich and Ledner': 655, 'fraud_Roberts-Beahan': 656, 'fraud_Schmeler-Howe': 657, 'fraud_Thompson-Gleason': 658, 'fraud_Murray Ltd': 659, 'fraud_Abbott-Rogahn': 660, 'fraud_Haley Group': 661, 'fraud_Hermiston, Russel and Price': 662, 'fraud_Lakin, Ferry and Beatty': 663, 'fraud_McCullough, Hudson and Schuster': 664, 'fraud_Zboncak LLC': 665, 'fraud_Kozey-Boehm': 666, 'fraud_Champlin, Rolfson and Connelly': 667, 'fraud_Weber, Thiel and Hammes': 668, 'fraud_Kozey-McDermott': 669, 'fraud_Strosin-Cruickshank': 670, 'fraud_Bednar Inc': 671, 'fraud_Hagenes, Hermann and Stroman': 672, 'fraud_Effertz, Welch and Schowalter': 673, 'fraud_Terry-Huel': 674, 'fraud_Wiegand-Lowe': 675, 'fraud_Kemmer-Reinger': 676, 'fraud_Mante Group': 677, 'fraud_Mueller, Gerhold and Mueller': 678, 'fraud_Kerluke PLC': 679, 'fraud_Runolfsdottir, Mueller and Hand': 680, 'fraud_Abbott-Steuber': 681, 'fraud_Ortiz Group': 682, 'fraud_Johnston-Casper': 683, 'fraud_Boyer-Haley': 684, 'fraud_Kutch Group': 685, 'fraud_Tromp Group': 686, 'fraud_Cummings Group': 687, 'fraud_Breitenberg LLC': 688, 'fraud_Turner LLC': 689, 'fraud_Rempel PLC': 690, 'fraud_Mosciski Group': 691, 'fraud_Kovacek Ltd': 692, 'fraud_Kessler Group': 693}
time_of_the_day = {'midnight': 1, 'morning': 2, 'afternoon': 3, 'evening': 4}
browser = {'trident': 1, 'safari': 2, 'firefox': 3, 'presto': 4, 'chrome': 5}
device = {'windows': 1, 'mac': 2, 'iphone': 3, 'android': 4, 'linux': 5, 'ipad': 6}


# Define the features
features = {
    'product_category': st.sidebar.selectbox('Product Category', options=['grocery_net', 'kids_pets', 'shopping_pos', 'home',
       'gas_transport', 'food_dining', 'entertainment', 'health_fitness',
       'shopping_net', 'travel', 'misc_pos', 'misc_net', 'grocery_pos',
       'personal_care']),
    'order_price': st.sidebar.number_input('Order Price'),
    'merchant': st.sidebar.selectbox('Merchant', options=['fraud_Runolfsson and Sons', 'fraud_Larkin Ltd',
       'fraud_Metz-Boehm', 'fraud_Quitzon-Goyette',
       'fraud_Turner and Sons', 'fraud_Jacobi and Sons',
       'fraud_Raynor, Reinger and Hagenes', 'fraud_Bechtelar-Rippin',
       'fraud_Brekke and Sons', 'fraud_Pouros, Walker and Spencer',
       'fraud_Grimes LLC', 'fraud_Erdman-Durgan',
       'fraud_Towne, Greenholt and Koepp',
       'fraud_Christiansen, Goyette and Schamberger',
       'fraud_Rodriguez Group', 'fraud_Corwin-Romaguera',
       'fraud_Conroy Ltd', 'fraud_Herzog Ltd',
       'fraud_Graham, Hegmann and Hammes', 'fraud_Schumm PLC',
       'fraud_Roob-Okuneva', 'fraud_Robel, Cummerata and Prosacco',
       'fraud_Nolan-Williamson', 'fraud_Berge-Hills',
       "fraud_O'Reilly, Mohr and Purdy",
       'fraud_Schaefer, Maggio and Daugherty', 'fraud_Kuphal-Bartoletti',
       'fraud_Bernier, Streich and Jewess', 'fraud_Bradtke PLC',
       'fraud_Stoltenberg-Beatty', 'fraud_Weimann, Kuhic and Beahan',
       'fraud_Frami Group', 'fraud_Schaefer, McGlynn and Bosco',
       'fraud_Bode-Schuster', 'fraud_Hills-Witting',
       'fraud_Reichert, Shanahan and Hayes', 'fraud_Reilly LLC',
       'fraud_Greenfelder, Bartoletti and Davis', 'fraud_Huel-Langworth',
       'fraud_Yost, Schamberger and Windler', 'fraud_Erdman-Kertzmann',
       'fraud_Kris-Weimann', 'fraud_Price Inc',
       'fraud_Moore, Williamson and Emmerich',
       'fraud_Fadel, Mertz and Rippin', 'fraud_Schuppe, Nolan and Hoeger',
       'fraud_Hudson-Ratke', 'fraud_Kutch, Hermiston and Farrell',
       'fraud_White and Sons', "fraud_Greenholt, O'Hara and Balistreri",
       'fraud_Predovic Inc', 'fraud_Weimann-Lockman', 'fraud_Barton LLC',
       'fraud_Schoen, Kuphal and Nitzsche',
       'fraud_Lowe, Dietrich and Erdman',
       'fraud_Zemlak, Tillman and Cremin', 'fraud_Homenick LLC',
       'fraud_Kilback LLC', 'fraud_Jakubowski Group',
       'fraud_Terry, Johns and Bins', 'fraud_Powlowski-Weimann',
       'fraud_Okuneva, Schneider and Rau', 'fraud_Streich Ltd',
       'fraud_Brown PLC', 'fraud_Bins-Howell',
       'fraud_Breitenberg-Hermiston', 'fraud_Daugherty LLC',
       'fraud_Schroeder, Hauck and Treutel', 'fraud_Hudson-Grady',
       'fraud_Howe Ltd', 'fraud_Koss and Sons', 'fraud_Yost-Rogahn',
       'fraud_Corwin-Gorczany', 'fraud_Reichert-Weissnat',
       'fraud_Kerluke-Abshire', 'fraud_Hermann-Gaylord',
       "fraud_Lesch, D'Amore and Brown", 'fraud_Block-Parisian',
       'fraud_Rolfson-Kunde', 'fraud_Bahringer, Bergnaum and Quitzon',
       'fraud_Goodwin-Nitzsche', 'fraud_Haag-Blanda',
       'fraud_Keeling-Crist', 'fraud_Koss, Hansen and Lueilwitz',
       'fraud_Jast-McDermott', 'fraud_Berge LLC', 'fraud_Jewess LLC',
       'fraud_Dickinson-Rempel', 'fraud_Stamm-Witting',
       'fraud_Hackett-Lueilwitz', "fraud_Schamberger-O'Keefe",
       'fraud_Mohr Inc', 'fraud_Kihn, Brakus and Goyette',
       'fraud_Erdman-Schaden', 'fraud_Rutherford-Mertz',
       'fraud_Stamm-Rodriguez', 'fraud_Stanton, Jakubowski and Baumbach',
       'fraud_Kiehn Inc', 'fraud_Gerlach Inc', 'fraud_Fahey Inc',
       'fraud_Reilly, Heaney and Cole', 'fraud_Hoppe, Harris and Bednar',
       'fraud_Cassin-Harvey', 'fraud_Ernser-Feest',
       'fraud_Heller, Gutmann and Zieme', 'fraud_Fritsch and Sons',
       'fraud_Bins-Tillman', 'fraud_Kozey-Kuhlman',
       "fraud_O'Hara-Wilderman", 'fraud_Goldner, Kovacek and Abbott',
       'fraud_Botsford PLC', 'fraud_Halvorson Group',
       'fraud_Heller-Langosh', 'fraud_Schuppe-Schuppe',
       'fraud_Veum-Koelpin', 'fraud_Schimmel-Olson',
       'fraud_Auer-Mosciski', 'fraud_Kub-Heaney',
       'fraud_Quitzon, Green and Bashirian', 'fraud_Cummings LLC',
       'fraud_Pfeffer and Sons', 'fraud_Wuckert-Walter',
       'fraud_Schmeler Inc', 'fraud_McDermott-Weimann',
       'fraud_Harris Inc', 'fraud_Pacocha-Bauch', 'fraud_Schroeder Group',
       'fraud_Roberts, Daniel and Macejkovic',
       'fraud_Welch, Rath and Koepp', 'fraud_Nitzsche, Kessler and Wolff',
       'fraud_Boyer-Reichert', 'fraud_Sporer Inc',
       'fraud_Volkman-Predovic', 'fraud_Beier and Sons',
       'fraud_Emmerich-Luettgen', 'fraud_Lesch Ltd',
       'fraud_Miller-Harris', 'fraud_Pagac LLC', 'fraud_Schoen Ltd',
       'fraud_Vandervort-Funk', 'fraud_Bailey-Morar',
       'fraud_Medhurst, Cartwright and Ebert', "fraud_O'Connell-Ullrich",
       'fraud_Altenwerth-Kilback', 'fraud_Dicki Ltd',
       'fraud_Eichmann, Bogan and Rodriguez', 'fraud_Bogisich Inc',
       'fraud_Smitham-Schiller', 'fraud_Zulauf LLC',
       'fraud_Shanahan-Lehner', 'fraud_Gulgowski LLC', 'fraud_Kuhic Inc',
       'fraud_Berge, Kautzer and Harris', 'fraud_Waters-Cruickshank',
       'fraud_Hahn, Bahringer and McLaughlin',
       'fraud_Reinger, Weissnat and Strosin', 'fraud_Bernhard Inc',
       'fraud_Kutch-Wilderman', 'fraud_Morissette LLC',
       'fraud_Huel, Hammes and Witting', 'fraud_Bashirian Group',
       'fraud_Padberg-Welch', 'fraud_Kiehn-Emmerich',
       'fraud_Runte, Green and Emard', 'fraud_Morissette PLC',
       'fraud_Zboncak Ltd', 'fraud_Hintz, Bauch and Smith',
       'fraud_Harris Group', 'fraud_Thiel PLC', 'fraud_Macejkovic-Lesch',
       'fraud_Nienow PLC', 'fraud_Ullrich Ltd',
       'fraud_Bernier, Volkman and Hoeger',
       'fraud_Bins, Balistreri and Beatty', 'fraud_Harber Inc',
       'fraud_Goyette-Gerhold', 'fraud_Parisian, Schiller and Altenwerth',
       'fraud_Herman Inc', 'fraud_Kilback Group',
       'fraud_Johnson, Runolfsdottir and Mayer', 'fraud_Swift PLC',
       'fraud_Cormier LLC', 'fraud_Auer-West',
       'fraud_Hettinger, McCullough and Fay',
       'fraud_Heathcote, Yost and Kertzmann', 'fraud_Miller-Hauck',
       'fraud_Schmitt Inc', 'fraud_Kuhn LLC', 'fraud_Torphy-Goyette',
       'fraud_Nader-Heller', 'fraud_Jerde-Hermann',
       'fraud_Streich, Dietrich and Barton', 'fraud_Treutel-King',
       'fraud_Stokes, Christiansen and Sipes',
       'fraud_Windler, Goodwin and Kovacek', 'fraud_Will Ltd',
       'fraud_Bahringer, Schoen and Corkery', 'fraud_Hills-Boyer',
       'fraud_Graham and Sons', 'fraud_Streich, Rolfson and Wilderman',
       'fraud_DuBuque LLC', 'fraud_Rippin-VonRueden',
       'fraud_Stiedemann Ltd', 'fraud_McCullough Group',
       'fraud_Ratke and Sons', 'fraud_Lind-Buckridge',
       'fraud_Conroy-Emard', 'fraud_McKenzie-Huels', 'fraud_Bednar Group',
       'fraud_Konopelski, Schneider and Hartmann', "fraud_O'Keefe-Wisoky",
       'fraud_Conroy-Cruickshank', 'fraud_Weber and Sons',
       'fraud_Lang, Towne and Schuppe', "fraud_Hamill-D'Amore",
       'fraud_Bernier and Sons', 'fraud_Moore, Dibbert and Koepp',
       'fraud_Leannon-Nikolaus', 'fraud_Jakubowski Inc',
       'fraud_Brown Inc', 'fraud_Stroman, Hudson and Erdman',
       'fraud_Romaguera, Cruickshank and Greenholt',
       'fraud_Hamill-Daugherty', 'fraud_Jaskolski-Vandervort',
       'fraud_Gottlieb, Considine and Schultz', 'fraud_Wilkinson PLC',
       'fraud_Heller PLC', 'fraud_Fadel-Hilpert',
       'fraud_Swaniawski, Lowe and Robel', 'fraud_Gottlieb Group',
       'fraud_Leffler-Goldner', 'fraud_Kuphal-Predovic',
       'fraud_Kutch, Steuber and Gerhold',
       'fraud_Reichert, Rowe and Mraz',
       "fraud_O'Connell, Botsford and Hand", 'fraud_Friesen-Ortiz',
       'fraud_Mante, Luettgen and Hackett', 'fraud_Rau and Sons',
       'fraud_Kihn, Abernathy and Douglas',
       'fraud_Turcotte, Batz and Buckridge',
       'fraud_Zboncak, Rowe and Murazik', 'fraud_Eichmann-Kilback',
       'fraud_Prohaska-Murray', 'fraud_Schaefer, Fay and Hilll',
       'fraud_Swaniawski, Nitzsche and Welch', 'fraud_Donnelly PLC',
       'fraud_Medhurst PLC', 'fraud_Rohan, White and Aufderhar',
       'fraud_Maggio-Fahey', 'fraud_Reichel LLC', 'fraud_Stracke-Lemke',
       'fraud_Monahan-Morar', 'fraud_Connelly-Carter',
       'fraud_Gibson-Deckow', 'fraud_Waelchi Inc', 'fraud_Bernhard-Lesch',
       'fraud_Wuckert-Goldner', 'fraud_Christiansen-Gusikowski',
       'fraud_Hagenes, Kohler and Hoppe', 'fraud_Friesen-Stamm',
       'fraud_Nienow, Barrows and Romaguera',
       'fraud_Raynor, Feest and Miller',
       'fraud_Haley, Jewess and Bechtelar', 'fraud_Huels-Hahn',
       'fraud_Dare, Fritsch and Zboncak', 'fraud_Bartoletti-Wunsch',
       'fraud_Hickle Group', 'fraud_Kautzer and Sons', 'fraud_Fisher Inc',
       'fraud_Denesik, Powlowski and Pouros', 'fraud_Stark-Batz',
       'fraud_Goyette Inc', 'fraud_Schumm, Bauch and Ondricka',
       'fraud_Jacobi Inc', 'fraud_Klocko, Runolfsdottir and Breitenberg',
       'fraud_Connelly, Reichert and Fritsch',
       'fraud_Wuckert, Wintheiser and Friesen',
       'fraud_Eichmann, Hayes and Treutel', 'fraud_Towne LLC',
       'fraud_Brown-Greenholt', 'fraud_Schmidt-Larkin',
       'fraud_Emmerich-Rau', 'fraud_Daugherty, Pouros and Beahan',
       'fraud_Hermann and Sons', 'fraud_Rowe, Batz and Goodwin',
       'fraud_Morissette-Schaefer', 'fraud_Larson-Moen',
       'fraud_Ebert-Daugherty', 'fraud_Terry Ltd', 'fraud_Dickinson Ltd',
       'fraud_Cronin, Kshlerin and Weber', 'fraud_Wilkinson Ltd',
       'fraud_Hammes-Beatty', 'fraud_Schiller, Blanda and Johnson',
       'fraud_Cartwright PLC', 'fraud_Padberg-Sauer', 'fraud_Gerhold LLC',
       'fraud_Hartmann, Rowe and Hermann', 'fraud_Mohr-Bayer',
       'fraud_Gislason Group', 'fraud_Beer-Jast',
       'fraud_Dare, Casper and Bartoletti', 'fraud_Mayert Group',
       'fraud_Kassulke PLC', 'fraud_Crist, Jakubowski and Littel',
       'fraud_Beier LLC', 'fraud_Rempel Inc', 'fraud_Collier Inc',
       'fraud_Jenkins, Hauck and Friesen', 'fraud_McGlynn-Jaskolski',
       'fraud_Goyette-Herzog', 'fraud_Jaskolski-Dibbert',
       'fraud_Ruecker-Mayert', 'fraud_Kris-Padberg', 'fraud_Klein Group',
       'fraud_Cruickshank-Mills', 'fraud_Hahn, Douglas and Schowalter',
       'fraud_Baumbach, Hodkiewicz and Walsh',
       'fraud_Reichert, Huels and Hoppe', 'fraud_Casper, Hand and Zulauf',
       'fraud_Turcotte, McKenzie and Koss',
       'fraud_Nienow, Ankunding and Collier',
       'fraud_Larkin, Stracke and Greenfelder', 'fraud_Ernser-Lynch',
       'fraud_Lubowitz-Walter', 'fraud_Friesen Inc',
       'fraud_Cummerata-Jones', 'fraud_Jast and Sons', 'fraud_Dooley Inc',
       'fraud_Altenwerth, Cartwright and Koss', 'fraud_Cummerata-Hilpert',
       'fraud_Kuphal-Toy', 'fraud_Kilback and Sons', 'fraud_Effertz LLC',
       'fraud_Roob, Conn and Tremblay', 'fraud_Heathcote LLC',
       'fraud_Rau-Grant', 'fraud_Greenholt Ltd', 'fraud_Lockman Ltd',
       'fraud_Sporer-Keebler', 'fraud_Beier-Hyatt', 'fraud_Wolf Inc',
       'fraud_Cormier, Stracke and Thiel',
       'fraud_Ritchie, Bradtke and Stiedemann',
       'fraud_Lind, Huel and McClure', 'fraud_Collier LLC',
       'fraud_Bruen-Yost', 'fraud_Adams-Barrows', 'fraud_Carroll PLC',
       'fraud_Koepp-Witting', 'fraud_Fritsch LLC',
       'fraud_Reilly and Sons', 'fraud_Champlin and Sons',
       'fraud_Willms, Kris and Bergnaum', 'fraud_Lynch-Mohr',
       'fraud_Kihn Inc', 'fraud_McDermott-Rice', 'fraud_Kling-Ernser',
       'fraud_Turcotte-Halvorson', 'fraud_Renner Ltd', 'fraud_Howe PLC',
       'fraud_Romaguera, Wehner and Tromp',
       'fraud_Kuhic, Bins and Pfeffer', 'fraud_Stark-Koss',
       'fraud_Bartoletti and Sons', 'fraud_Dach-Borer',
       'fraud_Parker, Nolan and Trantow', 'fraud_Volkman Ltd',
       'fraud_Murray-Smitham', 'fraud_Hermiston, Pacocha and Smith',
       'fraud_Gottlieb-Hansen', 'fraud_Haley, Batz and Auer',
       'fraud_Labadie, Treutel and Bode', 'fraud_Huels-Nolan',
       'fraud_Thiel-Thiel', 'fraud_Swaniawski, Bahringer and Ledner',
       'fraud_Cartwright-Harris', 'fraud_Feil-Morar',
       'fraud_Lockman, West and Runte', 'fraud_Kemmer-Buckridge',
       'fraud_Schuppe LLC', 'fraud_Koelpin and Sons',
       'fraud_Brown, Homenick and Lesch', 'fraud_Ledner-Pfannerstill',
       'fraud_Little Ltd', 'fraud_Ruecker Group',
       'fraud_Skiles-Ankunding', 'fraud_McDermott, Osinski and Morar',
       'fraud_Metz, Russel and Metz',
       'fraud_Schroeder, Wolff and Hermiston', 'fraud_Hackett Group',
       'fraud_Stehr, Jewess and Schimmel',
       'fraud_Bahringer, Osinski and Block', 'fraud_Hoppe-Parisian',
       'fraud_Corwin-Collins', 'fraud_Kling-Grant',
       'fraud_Stiedemann Inc', 'fraud_Witting, Beer and Ernser',
       'fraud_Friesen Ltd', 'fraud_Pouros-Conroy', 'fraud_Hintz-Bruen',
       'fraud_Kirlin and Sons', 'fraud_Mraz-Herzog', 'fraud_Bins-Rice',
       'fraud_Medhurst, Labadie and Gottlieb',
       'fraud_Bernhard, Grant and Langworth',
       'fraud_Monahan, Hermann and Johns', 'fraud_Emard Inc',
       'fraud_Greenholt, Jacobi and Gleason', 'fraud_Schaefer Ltd',
       'fraud_Hirthe-Beier', 'fraud_Funk Group',
       'fraud_Schultz, Simonis and Little',
       'fraud_Kovacek, Dibbert and Ondricka', 'fraud_Fisher-Schowalter',
       'fraud_Kuvalis Ltd', 'fraud_Denesik and Sons', 'fraud_Skiles LLC',
       'fraud_Kutch LLC', 'fraud_Tillman, Dickinson and Labadie',
       'fraud_Adams, Kovacek and Kuhlman',
       'fraud_Herman, Treutel and Dickens', 'fraud_Torp-Labadie',
       'fraud_Padberg-Rogahn', 'fraud_Baumbach, Feeney and Morar',
       'fraud_Schumm, McLaughlin and Carter', 'fraud_Medhurst Inc',
       'fraud_Labadie LLC', 'fraud_Hauck, Dietrich and Funk',
       'fraud_Heidenreich PLC', 'fraud_Lebsack and Sons',
       'fraud_Conroy, Balistreri and Gorczany', "fraud_Pacocha-O'Reilly",
       'fraud_Gaylord-Powlowski', 'fraud_Ankunding-Carroll',
       'fraud_Kunde-Sanford', 'fraud_Koepp-Parker', 'fraud_Kutch-Ferry',
       'fraud_Morar Inc', 'fraud_Schoen-Quigley', 'fraud_Huel Ltd',
       'fraud_Marvin-Lind', 'fraud_Gutmann, McLaughlin and Wiza',
       'fraud_Romaguera Ltd', 'fraud_Heaney-Marquardt', 'fraud_Roob LLC',
       'fraud_Torp-Lemke', 'fraud_Dibbert and Sons',
       'fraud_Buckridge PLC', 'fraud_Watsica LLC', 'fraud_Zemlak Group',
       'fraud_Hilpert-Conroy', 'fraud_Schulist Ltd',
       'fraud_Mosciski, Gislason and Mertz',
       'fraud_Baumbach, Strosin and Nicolas',
       'fraud_Kunze, Larkin and Mayert', 'fraud_Doyle Ltd',
       'fraud_Spinka Inc', 'fraud_Bogisich-Homenick', 'fraud_Boyer PLC',
       'fraud_Hills-Olson', 'fraud_Rutherford, Homenick and Bergstrom',
       'fraud_Lemke-Gutmann', 'fraud_Langosh, Wintheiser and Hyatt',
       'fraud_Dach-Nader', 'fraud_Olson, Becker and Koch',
       'fraud_Pollich LLC', 'fraud_Satterfield-Lowe', 'fraud_Dare-Marvin',
       'fraud_Bode-Rempel', 'fraud_Windler LLC', 'fraud_Dooley-Thompson',
       'fraud_Pfeffer LLC', 'fraud_Botsford Ltd', 'fraud_Spinka-Welch',
       'fraud_Kling Inc', 'fraud_Kuhic LLC', 'fraud_Gleason and Sons',
       'fraud_Ledner, Hartmann and Feest', 'fraud_Spencer-Runolfsson',
       'fraud_Rau-Robel', 'fraud_Kunze Inc', 'fraud_Crona and Sons',
       'fraud_Block-Hauck', 'fraud_Berge-Ullrich', 'fraud_Kutch and Sons',
       'fraud_Marks Inc', 'fraud_Deckow-Dare', 'fraud_Waelchi-Wolf',
       'fraud_Hayes, Marquardt and Dibbert', 'fraud_Fadel Inc',
       'fraud_Auer LLC', 'fraud_Dietrich-Fadel',
       'fraud_Durgan, Gislason and Spencer',
       'fraud_Hodkiewicz, Prohaska and Paucek',
       'fraud_Mosciski, Ziemann and Farrell',
       'fraud_Reichel, Bradtke and Blanda', 'fraud_Bauch-Blanda',
       'fraud_Turner, Ruecker and Parisian',
       'fraud_Bradtke, Torp and Bahringer', 'fraud_Schiller Ltd',
       'fraud_Gleason-Macejkovic', 'fraud_Schmeler, Bashirian and Price',
       'fraud_Dare-Gibson', 'fraud_Gutmann-Upton',
       'fraud_Rodriguez, Yost and Jenkins',
       'fraud_Feil, Hilpert and Koss', 'fraud_Kerluke Inc',
       'fraud_Lynch-Wisozk', 'fraud_Cole PLC', 'fraud_Romaguera and Sons',
       'fraud_Yost, Block and Koepp', 'fraud_Pacocha-Weissnat',
       'fraud_Balistreri-Nader', 'fraud_Paucek-Wiza',
       'fraud_Little, Gutmann and Lynch', 'fraud_Schmidt and Sons',
       'fraud_Kihn-Fritsch', 'fraud_Thiel Ltd',
       'fraud_Kilback, Nitzsche and Leffler',
       'fraud_Schneider, Hayes and Nikolaus', 'fraud_Kessler Inc',
       'fraud_Shields-Wunsch', 'fraud_VonRueden Group',
       'fraud_Connelly PLC', 'fraud_Ziemann-Waters', 'fraud_Sawayn PLC',
       'fraud_Wisozk and Sons', 'fraud_Rippin, Kub and Mann',
       'fraud_Kub PLC', 'fraud_Osinski Inc',
       'fraud_Tillman, Fritsch and Schmitt', 'fraud_Bogisich-Weimann',
       'fraud_Prosacco, Kreiger and Kovacek', 'fraud_Durgan-Auer',
       'fraud_Gutmann Ltd', "fraud_O'Keefe-Hudson", 'fraud_Upton PLC',
       'fraud_Welch Inc', 'fraud_Johns-Hoeger', 'fraud_Botsford and Sons',
       'fraud_Luettgen PLC', 'fraud_Smith-Stokes',
       'fraud_Schoen, Nienow and Bauch', 'fraud_Erdman-Ebert',
       'fraud_Nader-Maggio', 'fraud_Smitham-Boehm',
       'fraud_Kohler, Lindgren and Koelpin', 'fraud_Parker-Kunde',
       'fraud_Wiza, Schaden and Stark', 'fraud_Lynch Ltd',
       'fraud_Armstrong, Walter and Gottlieb', 'fraud_Bauch-Raynor',
       'fraud_Wilkinson LLC', 'fraud_Ruecker, Beer and Collier',
       'fraud_McCullough LLC', 'fraud_McLaughlin, Armstrong and Koepp',
       'fraud_Wiza LLC', 'fraud_Streich, Hansen and Veum',
       'fraud_Turner, Ziemann and Lehner',
       'fraud_Hyatt, Russel and Gleichner', 'fraud_Daugherty-Thompson',
       'fraud_Ferry, Lynch and Kautzer', 'fraud_Bahringer Group',
       'fraud_Block Group', 'fraud_Osinski, Ledner and Leuschke',
       'fraud_Ankunding LLC', 'fraud_Langworth, Boehm and Gulgowski',
       'fraud_Schmitt Ltd', 'fraud_Runte-Mohr',
       'fraud_Johnston, Nikolaus and Maggio', 'fraud_Pouros-Haag',
       'fraud_Simonis-Prohaska', 'fraud_McGlynn-Heathcote',
       'fraud_Barton Inc', 'fraud_Swift, Bradtke and Marquardt',
       'fraud_Becker, Harris and Harvey',
       'fraud_Hills, Hegmann and Schaefer', 'fraud_Leannon-Ward',
       'fraud_Parisian and Sons', 'fraud_Lehner, Mosciski and King',
       'fraud_Goyette, Howell and Collier',
       'fraud_Cremin, Hamill and Reichel',
       'fraud_Ferry, Reichel and DuBuque', 'fraud_Champlin-Casper',
       'fraud_Lubowitz, Terry and Stracke',
       'fraud_Walter, Hettinger and Kessler', 'fraud_Trantow PLC',
       'fraud_Eichmann-Russel', 'fraud_Lehner, Reichert and Mills',
       'fraud_Douglas, Schneider and Turner', 'fraud_Baumbach Ltd',
       'fraud_Watsica, Haag and Considine',
       'fraud_Koss, McLaughlin and Mayer', 'fraud_Barrows PLC',
       'fraud_Heller-Abshire', 'fraud_Boehm, Block and Jakubowski',
       'fraud_Abshire PLC', 'fraud_Kihn-Schuster',
       'fraud_Cole, Hills and Jewess', 'fraud_Volkman PLC',
       'fraud_Kertzmann LLC', 'fraud_Ritchie, Oberbrunner and Cremin',
       'fraud_Spencer PLC', 'fraud_Abernathy and Sons',
       'fraud_Donnelly LLC', 'fraud_Flatley-Durgan',
       'fraud_Torphy-Kertzmann', 'fraud_Harris, Gusikowski and Heaney',
       'fraud_Johns Inc', 'fraud_Kuhn Group',
       'fraud_Tromp, Kerluke and Glover', 'fraud_Williamson LLC',
       "fraud_Friesen-D'Amore", 'fraud_Kassulke Inc',
       'fraud_Jones, Sawayn and Romaguera',
       'fraud_Kerluke, Considine and Macejkovic', 'fraud_Kutch-Hegmann',
       'fraud_Boehm, Predovic and Reinger', 'fraud_Bahringer-Streich',
       'fraud_Lemke and Sons', 'fraud_Moen, Reinger and Murphy',
       'fraud_Rowe-Vandervort', 'fraud_Zieme, Bode and Dooley',
       'fraud_Flatley Group', 'fraud_Larson, Quitzon and Spencer',
       'fraud_Morissette, Weber and Wiegand', "fraud_Deckow-O'Conner",
       'fraud_Jast Ltd', 'fraud_Prosacco LLC',
       'fraud_Nicolas, Hills and McGlynn',
       'fraud_Towne, Walker and Borer', 'fraud_Kris-Kertzmann',
       'fraud_Little-Gleichner', 'fraud_Klocko LLC',
       'fraud_Douglas, DuBuque and McKenzie', 'fraud_Langworth LLC',
       'fraud_Reichel Inc', 'fraud_Tillman LLC',
       'fraud_Kling, Howe and Schneider', 'fraud_Bednar PLC',
       'fraud_Roberts, Ryan and Smith', 'fraud_Crooks and Sons',
       'fraud_Goldner-Lemke', 'fraud_Douglas-White', 'fraud_Hyatt-Blick',
       'fraud_Reynolds-Schinner', 'fraud_Kerluke, Kertzmann and Wiza',
       'fraud_Shields Inc', 'fraud_Kulas Group', 'fraud_Bahringer-Larson',
       'fraud_Dibbert-Green', 'fraud_Wintheiser, Dietrich and Schimmel',
       'fraud_Torp, Muller and Borer',
       'fraud_Monahan, Bogisich and Ledner', 'fraud_Roberts-Beahan',
       'fraud_Schmeler-Howe', 'fraud_Thompson-Gleason',
       'fraud_Murray Ltd', 'fraud_Abbott-Rogahn', 'fraud_Haley Group',
       'fraud_Hermiston, Russel and Price',
       'fraud_Lakin, Ferry and Beatty',
       'fraud_McCullough, Hudson and Schuster', 'fraud_Zboncak LLC',
       'fraud_Kozey-Boehm', 'fraud_Champlin, Rolfson and Connelly',
       'fraud_Weber, Thiel and Hammes', 'fraud_Kozey-McDermott',
       'fraud_Strosin-Cruickshank', 'fraud_Bednar Inc',
       'fraud_Hagenes, Hermann and Stroman',
       'fraud_Effertz, Welch and Schowalter', 'fraud_Terry-Huel',
       'fraud_Wiegand-Lowe', 'fraud_Kemmer-Reinger', 'fraud_Mante Group',
       'fraud_Mueller, Gerhold and Mueller', 'fraud_Kerluke PLC',
       'fraud_Runolfsdottir, Mueller and Hand', 'fraud_Abbott-Steuber',
       'fraud_Ortiz Group', 'fraud_Johnston-Casper', 'fraud_Boyer-Haley',
       'fraud_Kutch Group', 'fraud_Tromp Group', 'fraud_Cummings Group',
       'fraud_Breitenberg LLC', 'fraud_Turner LLC', 'fraud_Rempel PLC',
       'fraud_Mosciski Group', 'fraud_Kovacek Ltd', 'fraud_Kessler Group']),
    'time_of_the_day': st.sidebar.selectbox('Time of the Day', options=['midnight', 'morning', 'afternoon', 'evening']),
    'browser': st.sidebar.selectbox('Browser', options=['trident', 'safari', 'firefox', 'presto', 'chrome']),
    'device': st.sidebar.selectbox('Device', options=['windows', 'mac', 'iphone', 'android', 'linux', 'ipad']),
    'customer_job': st.sidebar.selectbox('Customer Job', options=
["software","mathematician", "scientist", "teaching", "airline", "medicine", "marketing",
"nature", "trader", "lawyer", "journalism", "finance", "civil", "executive", "media", "sports", "designer", "politician", "food", "other_engineering", "travel", "manager", "real_estate", "entertainment"])
}

# Load the model based on user selection
model_name = st.sidebar.selectbox('Select Model', options=['','Logistic Regression', 'Naive Bias', 'SVM', 'Random Forest', 'XGBoost', 'AdaBoost'])

with st.form(key='my_form'):
    submit_button = st.form_submit_button(label='Run Model')

if submit_button:
    if model_name == 'Logistic Regression':
        model = joblib.load('logisticreg.pkl')
    elif model_name == 'Naive Bias':
        model = joblib.load('naivebias.pkl')
    elif model_name == 'SVM':
        model = joblib.load('svm.pkl')
    elif model_name == 'Random Forest':
        model = joblib.load('randomforest.pkl')
    elif model_name == 'XGBoost':
        model = joblib.load('xgboost.pkl')
    elif model_name == 'AdaBoost':
        model = joblib.load('adaboost.pkl')
    else:
        model = None

    # Create a DataFrame from the features
    # print(features)
    data = {'product_category': product_category[features['product_category']], 'order_price': features['order_price'], 
            'merchant': merhcant[features['merchant']], 'time_of_the_day': time_of_the_day[features['time_of_the_day']], 
            'browser': browser[features['browser']], 'device': device[features['device']], 'customer_job': customer_job[features['customer_job']]}

    df = pd.DataFrame([data])

    # Predict the output
    if model != None:
        prediction = model.predict(df)
        for key, value in features.items():
            st.write(f"*{key}:* {value}")
        if prediction == 0:
            st.write(f'The transaction with the above details is termed as "Fraud Transaction"')
        else:
            st.write(f'The transaction with the above details is termed as "Non-fraud/Legit Transaction"')
    else:
        st.write(f'Please choose the Model')